dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: LcCET8vbNRth1DflxU3KuTNbNwdCtbqMvf1sgeRxeSVf+oA/jZZBjA8qgyGlLa5pNY1ntUeXODbTJ85Z6qCw5MSRJO35CiICvk+7PfG3+dpQLAgbm5VDhGyM9hH9KSLCGXlAafrt8UplPEVI+uz76FiusGQVYglmhfudHqaoMeIFcO9zSVJpdn3D6wE9wXZ+g8ugq6KFbRXi0e1oVyOWTO8Ke9rooM4HSAMKs9iUxys/9bO2etXA4SbcQlZyuwGQN4L8VT++g4g9UR/Z10q9bbf1GF2GvqxUifZ2GC5nOVWZTcVM/vvknWS3ksgylC+ToCj2b/vb/5y3EiIwszWJ1XJ9bJWLIJKUiFf5hPf2k0POhO7jV2JNHB5oicW2Lbcy8X7NqM0W5lFgsSBwU16MJSgN7qy/VqUpBb/8eUA1dJ4HsZ2nUIbe6j7Mp/QJJ/KDjbYWSTosrKvx6zmu5P+qkoIpyWFBZi2SppWNPHOtf5j0NaPr0SGci9aVkS9AOswPhm3aV5QmwJM3K8rhmZA0nFqOvSoWFMxlAIYPuW5k4u9lH8ius5AHR+lc4zuICCoqKsPn0SMeuoJg59WeQGodZbPOsF+pnob18w4idderIR32F37TgFyMXSwU7kV275hXyjr3azu9I5MlCxWpQk6JnKw2KKkepFP/w66FuM/r2wI=
