---
# tasks file for db
- name: Change mongo config file
  template:
    # template filename without folder templates
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongod
