---
# tasks file for db
- name: Change mongo config file
  template:
    # template filename without folder templates
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongod

### task for output env via ansible debug module
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"
