---
# tasks file for app
- name: Add unit file for Puma
  copy:
    # uses folder files
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma
- name: Add config for DB connection
  template:
    # uses folder templates
    src: db_config.j2
    dest: /home/appuser/db_config
    owner: appuser
    group: appuser

- name: enable puma
  systemd: name=puma enabled=yes


### task for output env via ansible debug module
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"
