---
- name: Configure mongodb
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
    - name: restart mongod
      service: name=mongod state=restarted

- name: Configure App
  hosts: app
  become: true
  tags: app-tag
  vars:
    db_host: 10.132.0.2
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted

- name: Deploy App && bundle install
  hosts: app
  # become: true
  tags: deploy-tag
  tasks:
    - name: Deploy reddit via git
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith

    - name: bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      notify: restart puma

  handlers:
    - name: restart puma
      become: true
      systemd: name=puma state=restarted
